#!/bin/bash

tips=(
"These $(tput smul)bright young things$(tput rmul) have just started college

young, enthusiastic, fashionable, or ambitious people"

"My assistant is a bit $(tput smul)wet behind the ears$(tput rmul). He still has a lot to learn.

young and inexperienced"

"I've just turned 40, and I'm $(tput smul)in the prime of my life$(tput rmul). I always go to the gym after work.

at my best; healthy and successful"

"Katie started learning piano when she was $(tput smul)knee-high to a grasshopper$(tput rmul).

very young

grasshopper：蚱蜢"

"Derek and Joan spent their $(tput smul)twilight years$(tput rmul) traveling the world.

the last years of someone's life"

"My grandpa got married again at the $(tput smul)ripe old age$(tput rmul) of 92.

very old age

ripe：成熟的"

"Sally first sang on stage at the $(tput smul)tender age$(tput rmul) of 7.

very young age

tender：嫩的"

"Damien's at that $(tput smul)awkward age$(tput rmul) and finds it hard to talk to people.

the period of adolescence when people feel very self-conscious"

"Many singer's voices $(tput smul)improve with age$(tput rmul).

get better as they got older"

"Harper regrets $(tput smul)losing touch with$(tput rmul) all her old school friends.

no longer being in contact with"

"I think Claire's found $(tput smul)a soulmate$(tput rmul). Both she and Don love reading.

the perfect person to be a friend or partner"

"I've $(tput smul)kept in touch with$(tput rmul) Lin since we left college 25 years ago.

continue to be in contact with"

"Marie and Pierre met through Isaac, $(tput smul)a mutual friend$(tput rmul) of theirs.

a shared friend of two people"

"Ramon and Tara $(tput smul)get on like a house on fire$(tput rmul). They're always talking and laughing.

get along extremely well; have a very good relationship"

"Mia and I have $(tput smul)drifted apart$(tput rmul) since she left our choir and started boxing instead.

slowing become less friendly or close to each other

choir：合唱团"

"I $(tput smul)struck up a friendship$(tput rmul) with Pete while we were in a cooking class last year.

become friends with

struck是strike的过去分词"

"My wife and I $(tput smul)hit it off$(tput rmul) immediately when we first met at a country music concert.

become friends very quickly"

"Donna was $(tput smul)a fair-weather friend$(tput rmul). She wouldn't help when my house flooded.

a friend who leaves you when you have difficulties"

"Cy and I $(tput smul)got off on the wrong foot$(tput rmul) on our date. He was an hour late and forgot my name.

started our relationship badly"

"Bob reminds me so much of his father. He is $(tput smul)a chip off the old block$(tput rmul).

very similar to someone in his family"

"Uncle Tony is $(tput smul)the black sheep of the family$(tput rmul). He's been to prison three times.

someone who brings shame to the family or is the odd one in the family"

"We're $(tput smul)bringing up$(tput rmul) our children to be kind to animals.

teaching a child how to behave"

"We're $(tput smul)a close-knit family$(tput rmul). We always meet up for birthdays and holidays.

a loyal and supportive family

knit：v. (knit,knit)（使）紧密"

"Curly hair $(tput smul)runs in our family$(tput rmul), and my daughter, mom, and I all have it.

is a common feature in our family"

"Leo $(tput smul)bears a striking resemblance$(tput rmul) to his grandfather.

looks extremely similar"

"Mateo and his brother Lucas are $(tput smul)like two peas in a pod$(tput rmul). I can't tell them apart.

extremely similar to each other"

"Karen is $(tput smul)the spitting image of$(tput rmul) that actor in the new sci-fi film.

almost identical to"

"You must eat something. You're $(tput smul)all skin and bones$(tput rmul).

too thin"

"Oscar is only 25, but he's already $(tput smul)getting thin on top$(tput rmul).

have no hair on top of head"

"Rita $(tput smul)looked like she'd seen a ghost$(tput rmul) after I told her my news.

looked very scared or shocked"

"Rachel $(tput smul)looked like a drowned rat$(tput rmul) after she got caught in the rain on her way home.

was very wet

drowned：淹死的"

"My aunt believed in $(tput smul)keeping up appearances$(tput rmul) despite having little money.

pretending that things are going well

keep sth <-> up：保持高水平"

"Domenica $(tput smul)looked the part$(tput rmul) for her first day of work at the bank.

was dressed in the right way"

"George arrived at the restaurant $(tput smul)immaculately groomed$(tput rmul) for his date with Cassie.

打扮得特别整洁"

"Nalini $(tput smul)never has a hair out of place$(tput rmul). She cares a lot about her appearance.

is extremely neat and well groomed

groomed：打扮的"

"Philip $(tput smul)was born with a silver spoon in his month$(tput rmul). He grew up in a castle in France.

was born into a wealthy family"

"Maxine is such $(tput smul)a highflier$(tput rmul). She's been promoted twice this year and is only 23.

a very talented and successful person"

"Danika's parents don't approve of Bob because he's from $(tput smul)the wrong side of the tracks$(tput rmul).

the wrong social background or part of town

not approve of：不同意、不喜欢"

"My parents $(tput smul)didn't have two pennies to rub together$(tput rmul), but we still had lots of fun.

were very poor

penny：英国的便士，0.1元
dime：美国的0.1元
cent：美国的0.01元"

"Lucia has $(tput smul)a vivid imagination$(tput rmul). Her artworks are so original.

an ability to think of exciting images and ideas

vivid: （想象力）丰富的"

"Norah is such $(tput smul)a fuddy-duddy$(tput rmul). She never wants to come out with us on Saturday night.

someone who is unwilling to try new things."

"Gustav has $(tput smul)a selfish streak$(tput rmul). He won't share his cookies with his friends.

streak：不好的性格"

"Arturo is so $(tput smul)two-faced$(tput rmul). He said he liked my haircut but told his friends he hated it.

两面派"

"My dad's just $(tput smul)an average Joe$(tput rmul). He enjoys burgers and fries, and loves watching baseball.

a stereotypical man who has simple tastes

stereotypical：符合刻板印象的"

"It was great to see Jasmine at the party. She's always $(tput smul)a barrel of laughs$(tput rmul).

a fun person or situation

barrel：圆桶"

"Bob is such $(tput smul)a crybaby$(tput rmul). He was very upset about not getting a perfect score.

someone who cries a lot without good reason"

"Zoe loves proving how much she knows. She's $(tput smul)too smart for her own good$(tput rmul).

annoyingly proud of her intelligence or knowledge 太陈独秀了"

"Noah is really $(tput smul)down to earth$(tput rmul). He earns lots of money, but he lives in a little cottage.

practical and unpretentious 接地气

unpretentious：不爱炫耀的"

"I know Rex looks a bit scary, but he $(tput smul)wouldn't hurt a fly$(tput rmul).

is completely harmless

scary：吓人的
fly：苍蝇"

"Claire is $(tput smul)a social butterfly$(tput rmul). She's always going to parties.

a very sociable person 交际花"

"My uncle's $(tput smul)a lone wolf$(tput rmul). He lives on his own in a cabin in the forest.

someone who prefers to live or work alone"

"Tony $(tput smul)wouldn't say boo to a goose$(tput rmul). He gets really shy when he talks to customers.

is very timid and nervous

timid：胆怯的"

"I do $(tput smul)not know boo$(tput rmul) about raising chickens.

know nothing about a topic. Frequently with 'about'."

"Jim's $(tput smul)a good egg$(tput rmul). He helped me to move last week.

an honest, reliable, or considerate person"

"Hassan is $(tput smul)the salt of the earth$(tput rmul). I saw him help an old lady cross the road.

kind, honest, and unpretentious 活雷锋

unpretentious：不张扬的"

"Debbie's $(tput smul)a tough cookie$(tput rmul). She doesn't mind when people criticize her work.

determined and physically or emotionally strong

tough：嚼不烂的，剽悍的"

"Kirsty remained $(tput smul)as cool as cucumber$(tput rmul) throughout her performance.

calm and relaxed"

"My kids think this TV show is $(tput smul)the best thing since sliced bread$(tput rmul).

extremely good"

"The ice cream at Giuseppe's parlor really is $(tput smul)the bee's knees$(tput rmul)!

the very best

parlor：只卖一种东西的店
knee：膝盖"

"My new TV is $(tput smul)miles ahead of$(tput rmul) my old one.

much more advanced than"

"The view from the top of the mountain is totally $(tput smul)out of this world$(tput rmul). You can see for miles.

amazing"

"We had a wonderful boat trip. $(tput smul)The frosting on the cake$(tput rmul) was seeing dolphins.

the best part of a good experience

frosting：糖霜，撒上去的东西"

"Losing my office job was $(tput smul)a blessing in disguise$(tput rmul). My new job is much more interesting.

something that seems bad, but is actually good

in disguise：伪装了的"

"Chan's store only sells watches that are $(tput smul)top of the line$(tput rmul).

the best quality"

"The burgers in Max's diner are $(tput smul)to die for$(tput rmul). And they're huge!

就算死了也要（拿到、吃到）"

"Abel is a $(tput smul)top-notch$(tput rmul) reporter. He's interviewed some really famous actors.

highest quality

notch：等级"

"Karolina's cake is $(tput smul)second to none$(tput rmul). It looks beautiful, and it tastes delicious.

far better than any others"

"Pete's habit of dropping litter $(tput smul)leaves a bad taste in my mouth$(tput rmul).

makes me feel very uncomfortable

litter：（乱扔的）垃圾"

"The weather in Hawaii $(tput smul)didn't live up to expectations$(tput rmul). It rained every day.

was not as good as expected"

"Country music is $(tput smul)not my cup of tea$(tput rmul). I prefer rock music.

not something I enjoy"

"Noah's old car is $(tput smul)past its prime$(tput rmul). He's been driving it for years.

in a bad condition, or too old

cf. the prime of my life"

"The museum in my town is $(tput smul)nothing to write home about$(tput rmul). There are very few exhibits.

not every impressive"

"Watching golf on TV is so boring. It's $(tput smul)like watching paint dry$(tput rmul).

extremely boring"

"His voice is OK, but he's $(tput smul)not going to set the world on fire$(tput rmul).

not going to be very exciting or successful

set sth on fire：把东西点燃"

"It's still $(tput smul)rough around the edges$(tput rmul), but this is my design for the park.

not perfect, in need of more work"

"Rita's TV is $(tput smul)on its last legs$(tput rmul). She's had it for over 10 years.

likely to stop working soon"

"We had been really looking forward to the meal, but thought the food was $(tput smul)a let-down$(tput rmul).

a disappointment"

"My old desktop computer is $(tput smul)past its sell-by date$(tput rmul). It takes a long time to start up.

in need of replacing"

"Clarita's new apartment is tiny. There's $(tput smul)not enough room to swing a cat$(tput rmul).

very little space

swing：摇摆"

"My colleagues all have terrible colds. They're $(tput smul)dropping like fries$(tput rmul)!

becoming sick, or stopping doing something, in large numbers"

"You're $(tput smul)barking up the wrong tree$(tput rmul) if you think I can help you with your homework.
I'm terrible at science.

wasting effort by following the wrong course of action

bark：狗叫"

"The half-mile run was $(tput smul)a two-horse race$(tput rmul) between Beatriz and Maria.

a competition with only two clear possible winners"

"I $(tput smul)chickened out of$(tput rmul) diving off the top board in the pool. It was too high.

was too scared to"

"I told my boss I won't finish my report today, but she still keeps $(tput smul)badgering me$(tput rmul) about it.

repeatedly telling me to do something

badger：纠缠"

"It really $(tput smul)gets my goat$(tput rmul) when someone eats smelly food on the train.

irritates me

irritate：使恼火"

"You can do anything now that you've finished college. $(tput smul)The world is your oyster$(tput rmul).

You have lots of opportunities

oyster：生蚝"

"Frank ate $(tput smul)the lion's share$(tput rmul) of the cake. There wasn't enough for us.

the largest part"

"This little pill is supposed to help you lose 20 pounds? Yeah, $(tput smul)in a pig's ear$(tput rmul) it does.

猪才相信

也可作in a pig's eye, in a pig's arse（屁股）"

"I don't like my job, but it $(tput smul)puts food on the table$(tput rmul).

provides enough money to pay for the most important things"

"Sharon always $(tput smul)spoon-feeds$(tput rmul) her staff. She tells them exactly what to do.

gives too much help to"

"Don't get so upset about burning the cookies. It's no use $(tput smul)crying over spilled milk$(tput rmul).

getting upset about something that has already happened

spilled：洒出来的"

"Jennifer is such $(tput smul)a couch potato$(tput rmul). She never goes out and watches TV all weekend instead.

a lazy person who watches too much TV"

"I don't know whether to apply for this job. Its looks really interesting but $(tput smul)it pays peanuts$(tput rmul).

the salary is very low"

"Asher is such $(tput smul)a butterfingers$(tput rmul). He is always dropping things.

a clumsy person who often drops things

clumsy：笨拙的"

"I'm really stressed! I think I $(tput smul)bit off more than I could chew$(tput rmul) when I took this promotion.

took on more responsibility than I could manage

bit：咬 chew：嚼"

"I wanted Jo to water my plants when I was on vacation, 
so I $(tput smul)buttered her up$(tput rmul) by saying her backyard looked nice.

praised or flattered her so she would do me a favor

flatter：奉承"

"Copies of Sadie's new novel are $(tput smul)selling like hotcakes$(tput rmul) after it got great reviews.

selling quickly in large numbers"

"You want to $(tput smul)walk on eggshells$(tput rmul) around Dylan. He gets upset so easily.

be very careful not to cause offense"

"My granddaughter is $(tput smul)the apple of my eye$(tput rmul). I'm so proud of her.

a person I am very fond or proud of

fond：喜爱"

"Fiona told me she doesn't like my new scooter. I think it's just $(tput smul)sour grapes$(tput rmul).

a jealous and bitter attitude

sour：酸的"
)


#echo "${tips[@]}"
